import { Movie } from './movieTypes';

export const MOVIE_DATABASE: Movie[] = [
  {
    id: '1', title: 'The Shawshank Redemption', titleRu: 'Побег из Шоушенка',
    year: 1994, genre: ['drama'], duration: 142, mood: ['thoughtful', 'nostalgic'],
    description: 'История надежды и дружбы за стенами тюрьмы.',
    director: 'Фрэнк Дарабонт', forCompany: 'any',
    timeOfDay: ['evening', 'night'], format: 'long',
  },
  {
    id: '2', title: 'Interstellar', titleRu: 'Интерстеллар',
    year: 2014, genre: ['scifi', 'drama'], duration: 169, mood: ['thoughtful', 'excited'],
    description: 'Путешествие сквозь червоточину ради спасения человечества.',
    director: 'Кристофер Нолан', forCompany: 'any',
    timeOfDay: ['evening', 'night'], format: 'long',
  },
  {
    id: '3', title: 'The Grand Budapest Hotel', titleRu: 'Отель «Гранд Будапешт»',
    year: 2014, genre: ['comedy', 'drama'], duration: 99, mood: ['happy', 'nostalgic'],
    description: 'Приключения легендарного консьержа и его юного протеже.',
    director: 'Уэс Андерсон', forCompany: 'any',
    timeOfDay: ['afternoon', 'evening'], format: 'medium',
  },
  {
    id: '4', title: 'Parasite', titleRu: 'Паразиты',
    year: 2019, genre: ['thriller', 'drama'], duration: 132, mood: ['excited', 'thoughtful'],
    description: 'Семья из трущоб проникает в жизнь богатых.',
    director: 'Пон Джун-хо', forCompany: 'pair',
    timeOfDay: ['evening', 'night'], format: 'long',
  },
  {
    id: '5', title: 'Amélie', titleRu: 'Амели',
    year: 2001, genre: ['comedy', 'romance'], duration: 122, mood: ['happy', 'calm'],
    description: 'Мечтательная официантка тайно улучшает жизни людей.',
    director: 'Жан-Пьер Жёне', forCompany: 'pair',
    timeOfDay: ['afternoon', 'evening'], format: 'long',
  },
  {
    id: '6', title: 'Whiplash', titleRu: 'Одержимость',
    year: 2014, genre: ['drama'], duration: 106, mood: ['excited'],
    description: 'Молодой барабанщик и его жестокий наставник.',
    director: 'Дэмьен Шазелл', forCompany: 'solo',
    timeOfDay: ['evening', 'night'], format: 'medium',
  },
  {
    id: '7', title: 'My Neighbor Totoro', titleRu: 'Мой сосед Тоторо',
    year: 1988, genre: ['comedy'], duration: 86, mood: ['calm', 'happy', 'nostalgic'],
    description: 'Две сестры обнаруживают волшебных лесных существ.',
    director: 'Хаяо Миядзаки', forCompany: 'any',
    timeOfDay: ['morning', 'afternoon'], format: 'short',
  },
  {
    id: '8', title: 'Drive', titleRu: 'Драйв',
    year: 2011, genre: ['action', 'thriller'], duration: 100, mood: ['calm', 'excited'],
    description: 'Немногословный водитель втягивается в криминальный мир.',
    director: 'Николас Виндинг Рефн', forCompany: 'solo',
    timeOfDay: ['night'], format: 'medium',
  },
  {
    id: '9', title: 'The Breakfast Club', titleRu: 'Клуб «Завтрак»',
    year: 1985, genre: ['comedy', 'drama'], duration: 97, mood: ['nostalgic', 'thoughtful'],
    description: 'Пять подростков на субботней отработке.',
    director: 'Джон Хьюз', forCompany: 'group',
    timeOfDay: ['afternoon', 'evening'], format: 'medium',
  },
  {
    id: '10', title: 'Spirited Away', titleRu: 'Унесённые призраками',
    year: 2001, genre: ['drama'], duration: 125, mood: ['thoughtful', 'nostalgic'],
    description: 'Девочка попадает в мир духов и должна найти путь домой.',
    director: 'Хаяо Миядзаки', forCompany: 'any',
    timeOfDay: ['evening'], format: 'long',
  },
  {
    id: '11', title: 'In the Mood for Love', titleRu: 'Любовное настроение',
    year: 2000, genre: ['romance', 'drama'], duration: 98, mood: ['sad', 'nostalgic', 'calm'],
    description: 'Двое соседей подозревают, что их супруги имеют роман.',
    director: 'Вонг Кар-Вай', forCompany: 'solo',
    timeOfDay: ['night'], format: 'medium',
  },
  {
    id: '12', title: 'Mad Max: Fury Road', titleRu: 'Безумный Макс: Дорога ярости',
    year: 2015, genre: ['action', 'scifi'], duration: 120, mood: ['excited'],
    description: 'Гонка за выживание в постапокалиптическом мире.',
    director: 'Джордж Миллер', forCompany: 'group',
    timeOfDay: ['evening', 'night'], format: 'medium',
  },
  {
    id: '13', title: 'Lost in Translation', titleRu: 'Трудности перевода',
    year: 2003, genre: ['drama', 'comedy'], duration: 102, mood: ['calm', 'sad', 'nostalgic'],
    description: 'Двое одиноких американцев находят друг друга в Токио.',
    director: 'София Коппола', forCompany: 'solo',
    timeOfDay: ['night'], format: 'medium',
  },
  {
    id: '14', title: 'The Social Network', titleRu: 'Социальная сеть',
    year: 2010, genre: ['drama'], duration: 120, mood: ['excited', 'thoughtful'],
    description: 'История создания Facebook.',
    director: 'Дэвид Финчер', forCompany: 'solo',
    timeOfDay: ['afternoon', 'evening'], format: 'medium',
  },
  {
    id: '15', title: 'Coco', titleRu: 'Тайна Коко',
    year: 2017, genre: ['comedy', 'drama'], duration: 105, mood: ['happy', 'sad', 'nostalgic'],
    description: 'Мальчик попадает в красочный мир мёртвых.',
    director: 'Ли Анкрич', forCompany: 'group',
    timeOfDay: ['afternoon', 'evening'], format: 'medium',
  },
];
