-- Исторически здесь создавались public.rate_limits (key, count, reset_at) и
-- public.check_and_increment_rate_limit. На проде так не осталось:
--   * лимит Kino-app живёт в kino.rate_limits + kino.check_and_increment_rate_limit
--     (20260520000000_baseline_kino_schema.sql), в public — тонкая обёртка
--     (20260829141000_expose_rate_limit_in_public.sql);
--   * public.rate_limits на проде — (key, window_start, count) для
--     public.check_rate_limit Technical-language (20260528123333).
-- Старая версия этого файла создавала public.rate_limits не той формы, и
-- 20260528 молча пропускал CREATE TABLE IF NOT EXISTS — check_rate_limit падал
-- на чистой базе. Поэтому файл оставлен пустым (версия уже применена на проде).
SELECT 1;
